Sc 41 create custom button component
brandonyhchan/Bean-Here pull request #52
Opened 2024-09-12 02:06 UTC by kairen2000

## Describe your changes (point form)

- created the button component
- added an example page which we can delete later but its to show how the buttons work
- edited the theme for buttons so that the font size is consistent with all sizes
- Kept the "type" prop as the substitute for classname which we used in our previous spire-coffee repo
^ and we can use that if there are other changes that we want to use for things that cannot be added into the theme or things we aren't sure we want applied for all buttons. I used width as an example, but can be changed to padding etc

## Jira Ticket 
[SC-41](https://webdevgang.atlassian.net/browse/SC-41)

## Include any Screenshots/Videos if relevant 

how the buttons look like on the example page (i just copied and pasted it into favorites page to show it)

https://github.com/user-attachments/assets/d0a90eff-1f07-4d91-9098-4e29b897de8b

## Any other reminders reviewers should know? (`npm i`)

Yes you need to run an `npm i` for the loading button package

2024-09-12 02:07 UTC, kairen2000 commented on spire-coffee/src/component/CustomButton.tsx
> +  type = "",
Kept this as empty string because if we dont want to apply any css class this should be empty

2024-09-12 02:32 UTC, brandonyhchan commented on spire-coffee/src/pages/cafe/TestButtons.tsx
We probably don't need to add this file, you did have the video which is nice

2024-09-12 02:32 UTC, brandonyhchan commented on spire-coffee/src/component/customButton.module.scss
Pretty sure these can be applied with mui, don't need to use css (or scss) at all unless absolutely necessary

2024-09-12 02:33 UTC, kairen2000 commented on spire-coffee/src/component/customButton.module.scss
it can be but i didnt want to apply it cuz i dont know what size we want to make the buttons, should i just apply it and then we can change if necessary?

2024-09-12 02:34 UTC, kairen2000 commented on spire-coffee/src/pages/cafe/TestButtons.tsx
okay sounds good ill delete it!

2024-09-12 02:35 UTC, brandonyhchan requested changes
I think part of the ticket was to replace the buttons we currently have in the `Login` and `SignUp` pages, and those would serve as a "demo". 

There are also other buttons around our app atm (ie in the search bar) that might need to be incorporated? Or another component for button icons, not too sure how to handle that cc @bettyanhn

2024-09-12 03:28 UTC, kairen2000 commented
using the style prop to change the colors of the button
![image](https://github.com/user-attachments/assets/1759c5d4-279d-4ba3-ba61-542f22e7dc4a)

2024-09-15 02:59 UTC, bettyanhn approved these changes
lgtm

2024-09-19 06:23 UTC, merged