Sc 82 create sort menu
brandonyhchan/Bean-Here pull request #55
Opened 2024-09-22 09:35 UTC by bettyanhn

## Describe your changes (point form)
* Add sort menu to desktop next to explore bar
* Add sort options to filter sidebar in mobile view
* Update params for search to include sort options
## Jira Ticket 
82

## Include any Screenshots/Videos if relevant 

## Any other reminders reviewers should know? (`npm i`)
Please help testing

2024-09-23 03:20 UTC, bettyanhn commented
I also fixed pagination styling and the card overlap issue

2024-09-23 08:30 UTC, bettyanhn commented
card is now clickable again and doesn't overlap

2024-09-25 02:12 UTC, brandonyhchan approved these changes

2024-09-25 02:12 UTC, brandonyhchan requested changes
havent looked at this yet

2024-09-25 02:40 UTC, brandonyhchan approved these changes

2024-09-25 02:40 UTC, merged